/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramSetupRouteImport } from './routes/api/public/telegram/setup'
import { Route as ApiPublicTelegramAuthRouteImport } from './routes/api/public/telegram/auth'
import { Route as ApiPublicCronNotifyRouteImport } from './routes/api/public/cron/notify'
import { Route as ApiPublicCronDrawRouteImport } from './routes/api/public/cron/draw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramSetupRoute = ApiPublicTelegramSetupRouteImport.update({
  id: '/api/public/telegram/setup',
  path: '/api/public/telegram/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramAuthRoute = ApiPublicTelegramAuthRouteImport.update({
  id: '/api/public/telegram/auth',
  path: '/api/public/telegram/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotifyRoute = ApiPublicCronNotifyRouteImport.update({
  id: '/api/public/cron/notify',
  path: '/api/public/cron/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDrawRoute = ApiPublicCronDrawRouteImport.update({
  id: '/api/public/cron/draw',
  path: '/api/public/cron/draw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/draw': typeof ApiPublicCronDrawRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/draw': typeof ApiPublicCronDrawRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/draw': typeof ApiPublicCronDrawRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/telegram/auth': typeof ApiPublicTelegramAuthRoute
  '/api/public/telegram/setup': typeof ApiPublicTelegramSetupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/cron/draw'
    | '/api/public/cron/notify'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/cron/draw'
    | '/api/public/cron/notify'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/draw'
    | '/api/public/cron/notify'
    | '/api/public/telegram/auth'
    | '/api/public/telegram/setup'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronDrawRoute: typeof ApiPublicCronDrawRoute
  ApiPublicCronNotifyRoute: typeof ApiPublicCronNotifyRoute
  ApiPublicTelegramAuthRoute: typeof ApiPublicTelegramAuthRoute
  ApiPublicTelegramSetupRoute: typeof ApiPublicTelegramSetupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/setup': {
      id: '/api/public/telegram/setup'
      path: '/api/public/telegram/setup'
      fullPath: '/api/public/telegram/setup'
      preLoaderRoute: typeof ApiPublicTelegramSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/auth': {
      id: '/api/public/telegram/auth'
      path: '/api/public/telegram/auth'
      fullPath: '/api/public/telegram/auth'
      preLoaderRoute: typeof ApiPublicTelegramAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify': {
      id: '/api/public/cron/notify'
      path: '/api/public/cron/notify'
      fullPath: '/api/public/cron/notify'
      preLoaderRoute: typeof ApiPublicCronNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/draw': {
      id: '/api/public/cron/draw'
      path: '/api/public/cron/draw'
      fullPath: '/api/public/cron/draw'
      preLoaderRoute: typeof ApiPublicCronDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronDrawRoute: ApiPublicCronDrawRoute,
  ApiPublicCronNotifyRoute: ApiPublicCronNotifyRoute,
  ApiPublicTelegramAuthRoute: ApiPublicTelegramAuthRoute,
  ApiPublicTelegramSetupRoute: ApiPublicTelegramSetupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
